[package]
name = "lambda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.9"

[build-dependencies]
cc = "1.0.78"

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
